# ─────────────────────────────────────────────
# Font
# ─────────────────────────────────────────────

font_family JetBrainsMono Nerd Font
font_size 13.0


# ─────────────────────────────────────────────
# Window
# ─────────────────────────────────────────────

window_padding_width 10
background_opacity 0.99
background_blur 1
hide_window_decorations yes


# ─────────────────────────────────────────────
# Cursor
# ─────────────────────────────────────────────

cursor_shape block
cursor_blink_interval 0
cursor #ffffff


# ─────────────────────────────────────────────
# Tabs
# ─────────────────────────────────────────────

tab_bar_edge top
tab_bar_style powerline


# ─────────────────────────────────────────────
# Behaviour
# ─────────────────────────────────────────────

paste_actions no-op


# ─────────────────────────────────────────────
# Keybinds
# ─────────────────────────────────────────────

# Text editing


# Pane navigation
map cmd+left neighboring_window left
map cmd+right neighboring_window right
map cmd+up neighboring_window up
map cmd+down neighboring_window down


# Pane management
map cmd+enter launch --location=hsplit --cwd=current
map cmd+w close_tab


# Pane resizing
map cmd+shift+up    resize_window taller
map cmd+shift+down  resize_window shorter
map cmd+shift+left  resize_window narrower
map cmd+shift+right resize_window wider


# Tabs
map cmd+opt+left previous_tab
map cmd+opt+right next_tab
map cmd+t new_tab


# ─────────────────────────────────────────────
# Remote Control
# ─────────────────────────────────────────────

allow_remote_control yes
listen_on unix:/tmp/kitty


# ─────────────────────────────────────────────
# Theme
# ─────────────────────────────────────────────

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
