

enabled_layouts splits

# ─────────────────────────────────────────────
# Font
# ─────────────────────────────────────────────

font_family JetBrainsMono Nerd Font
font_size 13.0


# ─────────────────────────────────────────────
# Window
# ─────────────────────────────────────────────

window_padding_width 10
# background_opacity 0.95
hide_window_decorations yes


# ─────────────────────────────────────────────
# Cursor
# ─────────────────────────────────────────────

cursor_shape block
cursor_blink_interval 0
# cursor #ffffff


# ─────────────────────────────────────────────
# Tabs
# ─────────────────────────────────────────────

tab_bar_edge top
tab_bar_style powerline


# ─────────────────────────────────────────────
# Behaviour
# ─────────────────────────────────────────────

paste_actions no-op
map cmd+shift+f toggle_fullscreen

# ─────────────────────────────────────────────
# Keybinds
# ─────────────────────────────────────────────

# Session
# map cmd+s save_as_session --use-foreground-process --relocatable --save-only ~/.config/kitty/session.conf
# map cmd+shift+r goto_session ~/.config/kitty/session.conf

# Text editing

map cmd+up scroll_page_up
map cmd+down scroll_page_down

# Command (line movement)
map cmd+left      send_text all \x01
map cmd+right     send_text all \x05
map cmd+backspace send_text all \x15
map cmd+delete    send_text all \x04

# Option (word movement)
map alt+left      send_text all \eb
map alt+right     send_text all \ef
map alt+backspace send_text all \x17
map alt+delete    send_text all \x04


# Pane navigation
map cmd+ctrl+left  neighboring_window left
map cmd+ctrl+right neighboring_window right
map cmd+ctrl+up    neighboring_window up
map cmd+ctrl+down  neighboring_window down


# Pane management
map cmd+enter launch --location=hsplit --cwd=current
map cmd+shift+enter launch --location=vsplit --cwd=current
map cmd+w close_window

# Pane resizing
map cmd+shift+up    resize_window taller
map cmd+shift+down  resize_window shorter
map cmd+shift+left  resize_window wider
map cmd+shift+right resize_window narrower


# Tabs
map cmd+t new_window
map cmd+t new_tab

confirm_os_window_close 0

map cmd+opt+left previous_tab
map cmd+opt+right next_tab

map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9


# ─────────────────────────────────────────────
# Remote Control
# ─────────────────────────────────────────────

allow_remote_control yes
listen_on unix:/tmp/kitty


# ─────────────────────────────────────────────
# Theme
# ─────────────────────────────────────────────

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME
