# ─────────────────────────────────────────────
# Font
# ─────────────────────────────────────────────

font_family JetBrainsMono Nerd Font
font_size 13.0


# ─────────────────────────────────────────────
# Window
# ─────────────────────────────────────────────

window_padding_width 10
background_opacity 0.95
hide_window_decorations yes


# ─────────────────────────────────────────────
# Cursor
# ─────────────────────────────────────────────

cursor_shape block
cursor_blink_interval 0
cursor #ffffff


# ─────────────────────────────────────────────
# Tabs
# ─────────────────────────────────────────────

tab_bar_edge top
tab_bar_style powerline


# ─────────────────────────────────────────────
# Behaviour
# ─────────────────────────────────────────────

paste_actions no-op
map cmd+shift+f toggle_fullscreen

# ─────────────────────────────────────────────
# Keybinds
# ─────────────────────────────────────────────

# Text editing

# Command (line movement)
map cmd+left      send_text all \x01
map cmd+right     send_text all \x05
map cmd+backspace send_text all \x15
map cmd+delete    send_text all \x04

# Option (word movement)
map alt+left      send_text all \eb
map alt+right     send_text all \ef
map alt+backspace send_text all \x17
map alt+delete    send_text all \x04


# Pane navigation
map cmd+ctrl+left  neighboring_window left
map cmd+ctrl+right neighboring_window right
map cmd+ctrl+up    neighboring_window up
map cmd+ctrl+down  neighboring_window down


# Pane management
map cmd+enter launch --location=hsplit --cwd=current
map cmd+shift+enter launch --location=vsplit --cwd=current
map cmd+w close_window

# Pane resizing
map cmd+shift+up    resize_window taller
map cmd+shift+down  resize_window shorter
map cmd+shift+left  resize_window narrower
map cmd+shift+right resize_window wider


# Tabs
map cmd+opt+left previous_tab
map cmd+opt+right next_tab
map cmd+t new_tab


# ─────────────────────────────────────────────
# Remote Control
# ─────────────────────────────────────────────

allow_remote_control yes
listen_on unix:/tmp/kitty


# ─────────────────────────────────────────────
# Theme
# ─────────────────────────────────────────────

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
